apiVersion: apps/v1
kind: Deployment
metadata:
  name: skyliht-bot-db-controller
  namespace: skylight-bot-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-controller
  template:
    metadata:
      labels:
        app: db-controller
    spec:
      containers:
      - name: controller
        image: docker.io/hafifbilgiler/dbcontroller:3.7  #3.5
        imagePullPolicy: Always
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: dbname
