apiVersion: v1
kind: Secret
metadata:
  name: iyzico-secret
  namespace: skylight-bot-v2
type: Opaque
stringData:
  api-key: "4HCFCqXWrK60PhzyzHr2HPQctHpTzqxn"
  secret-key: "7PDad2aKJDxzSpOOCvg2ifdLlxB3k2S8"
  monthly-plan-code: "7PDad2aKJDxzSpOOCvg2ifdLlxB3k2S8"