apiVersion: v1
kind: Secret
metadata:
  name: iyzico-secret
  namespace: skylight-bot
type: Opaque
stringData:
  api-key: "4HCFCqXWrK60PhzyzHr2HPQctHpTzqxn"
  secret-key: "7PDad2aKJDxzSpOOCvg2ifdLlxB3k2S8"
  monthly-plan-code: "IYZICO_MONTHLY_PLAN_CODE_BURAYA"